language: ruby
rvm:
  - 2.3.0
before_script:
  - sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake ci:tests
services:
  - postgresql
notifications:
    email: false

deploy:
    provider: heroku
    api_key:
      secure: VVdvv74FGX83m1FLqBtTOF5JVEWjPVBCOrPbVO05j7KsM4pMPeZwmZiHECdVa+ZOFqRsw8RZNvoxmz6oZPND9tLCz1gNh8m2qo+1bKAX3GU4Rs8GSni9ROSXl1r3R92/I3ENbDnMbFZH4I3GoBgdzQdFhZ5blOLawTLpFC76Jm57NmaZfL3eXeO8MCHbvxjgwphk+Tf5tu6wSeOOcbFMYjBAw3QFGzkCaQOJTZazFnBzoWH2dBXPstyKnJeOwM/o03HFH11qnzCTZK83SqNzv9wg5M0BOYCpBuqnqj1ppRWSxxQjbmYx3I/TU884dFGjuHfilImDpjeU9CMTGRhVXI6PNdqLCELH9nvhZOftv8M5DvTKEUqDcE1b3+MbQ1X4FnRCbyayDoLqUYEalDYiU+pE20bsf9qiZfp8+8OkBTcgqk5+Ah5Q7lWktDHyAZ5Bd8mty/CvHCPgD1fPHyUaPETq1qALGiKe9e0G9NCb7h3DjBRLqF4TNyKejX7DpTIxUzAPxcDKqKunTBNJ24Szo9NFnCbm4hBQVbhlCmXL+t1UAtO/+zs5MQV5e+EmbCb5sC7IOLdTmTAUw3ejDYBa+vAMx4Zv4d/OsfvU4edNYlI/IffYftxYDlqr19QvTcGkx9B/RD1/4s1/BySupXhuuvOTt2paPTlaIVNZ0A7/P/0=
    app:
      develop: quizmasterone
    on:
      repo: CraftAcademy/quizmaster
    run:
      - "rails db:migrate"
